### ISSUE TITLE
nicotine+ crashes some time after launch

### ISSUE THREAD

**Issue by 11ph22il** [nicotine-plus/nicotine-plus#2341]
Nicotine+ version:  3.3.0.dev4 
Operating System/Distribution: Windows 10 21H2 (OS Build 19044.2486)

### Describe the bug

Nicotine gives the following error some seconds after opening:

```
Nicotine+ Version: 3.3.0.dev4
GTK Version: 4.8.2
Python Version: 3.10.9 (win32)

Type: <class 'TypeError'>
Value: '<' not supported between instances of 'method' and 'method'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 740, in raise_exception
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 953, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 266, in _run_scheduler
```

### Expected behavior

Normal use, no crash

### Steps to reproduce the bug

Start nicotine by opening **Nicotine+.exe**

### Additional context
![image](https://user-images.githubusercontent.com/166390/213955899-9dc23766-49b4-4a96-83c5-645f2cdab0cc.png)

**Comment by slook** [comment]
It sounds like a crash that was fixed in https://github.com/nicotine-plus/nicotine-plus/commit/1c1e1b2a7d3ab046e0f701e82748f32193a8da9f but the Windows builds are delayed for a few days due to a problem with the action runners.

Thanks for reporting.

**Comment by 11ph22il** [comment]
Oh I see that, I've downloaded this build you sent, but it isn't launching, taking a look at Task Manager, gdbus.exe just flashes

> It sounds like a crash that was fixed in [1c1e1b2](https://github.com/nicotine-plus/nicotine-plus/commit/1c1e1b2a7d3ab046e0f701e82748f32193a8da9f) but the Windows builds are delayed for a few days due to a problem with the action runners.
> 
> You could try updating to the latest build https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows not sure if it will give you the most recent or not.
> 
> Thanks for reporting.

**Comment by mathiascode** [comment]
Can you try the latest test build? It works fine on my Windows 11 machine.
https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by tuhanayim** [comment]
> Can you try the latest test build? It works fine on my Windows 11 machine. https://nicotine-plus.org/doc/TESTING.html#windows

I tested it, still crashes if `Minimize to tray on startup` is disabled. Probably the same error as OP's (I can't find logs anywhere).

**Comment by mathiascode** [comment]
Just to confirm, does this only happen in the latest unstable builds for Windows? Not the stable version?

It seems like it crashes outside of Python, so there won't be any logs by default.

**Comment by tuhanayim** [comment]
Only in latest unstable. Stable releases are working fine.

**Comment by mathiascode** [comment]
Did you mean when `Minimize to tray on startup` is enabled? That would make sense, since the tray icon hasn't been implemented in the unstable Windows builds yet.

Does Nicotine+ stay in the task manager after starting it?

**Comment by tuhanayim** [comment]
> Did you mean when `Minimize to tray on startup` is enabled? That would make sense, since the tray icon hasn't been implemented in the unstable Windows builds yet.
> 
> Does Nicotine+ stay in the task manager after starting it?

No, it only crashes when `Minimize to tray on startup` setting is **disabled**. That makes sense because OP's stack trace shows `gtkgui` folder. Even though there's no system tray implementation in GTK4 for Windows, it stays open.

Here's a video:
https://user-images.githubusercontent.com/108196023/215343343-ca07e931-5d58-44cc-8cf1-78ccf45f1647.mp4

**Comment by mathiascode** [comment]
OP's original issue is a different one that was fixed a few days ago.

Thanks for the screen recording, I suppose Nicotine+ crashes when attempting to show the main window. Can you download the latest unstable build (since https://github.com/nicotine-plus/nicotine-plus/commit/d5f7a8eda603b72fd3030135964d5cccfc7fbf39) and verify if it crashes regardless of what `Minimize to tray on startup` is set to.

**Comment by tuhanayim** [comment]
> OP's original issue is a different one that was fixed a few days ago (in https://github.com/nicotine-plus/nicotine-plus/commit/1c1e1b2a7d3ab046e0f701e82748f32193a8da9f).

Oh, I thought the problem was the same since it's crashing when trying to show UI made sense to me, sorry.

> Can you download the latest unstable build (since https://github.com/nicotine-plus/nicotine-plus/commit/d5f7a8eda603b72fd3030135964d5cccfc7fbf39) and verify if it crashes regardless of what Minimize to tray on startup is set to.

Yes, now it crashes in both situations.

**Comment by mathiascode** [comment]
Thanks, I'll prepare a special build with console logging enabled so we can debug this further.

**Comment by mathiascode** [comment]
Can you download windows-x86_64-package here, and start Nicotine+.exe in the Windows Console? It should hopefully log something before it crashes. https://github.com/mathiascode/nicotine-plus/actions/runs/4038037974

**Comment by tuhanayim** [comment]
<details>
  <summary>Execution Output</summary>

```ps1
❯ .\Nicotine+.exe
[2023-01-29 22:00:29] Loading Python 3.10.9
[2023-01-29 22:00:29] Loading Nicotine+ 3.3.0.dev4
[2023-01-29 22:00:30] Loading GTK 4.8.3
Windows fatal exception: code 0x800706b5

Thread 0x00002e84 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 280 in _run_scheduler
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 953 in run
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00000ef0 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/ui.py", line 49 in __init__
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 79 in __init__
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 836 in on_activate
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py", line 42 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 83 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 101 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 215 in run
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 34 in load_module
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 38 in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 18 in run
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 139 in run
[2023-01-29 22:00:32] Loaded plugin Nicotine+ Commands
[2023-01-29 22:00:32] Loading plugin system
[2023-01-29 22:00:32] Loaded plugin Multi Paste
[2023-01-29 22:00:32] Loaded plugin Now Playing Search
[2023-01-29 22:00:32] Listening on port: 2234
[2023-01-29 22:00:32] Connecting to server.slsknet.org:2242
[2023-01-29 22:00:32] Rescanning shares…
[2023-01-29 22:00:32] 98 folders found before rescan, rebuilding…
[2023-01-29 22:00:32] Connected to server server.slsknet.org:2242, logging in…
[2023-01-29 22:00:32] Rescan complete: 98 folders found
Windows fatal exception: access violation

Thread 0x000010d4 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 202 in get_services
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 287 in _find_service
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 313 in _update_port_mapping
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 367 in add_port_mapping
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 1216 in _process_server_input
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2081 in _process_conn_incoming_messages
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2020 in _process_ready_input_socket
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2070 in _process_ready_sockets
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2251 in run
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00002cc0 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/cli.py", line 82 in _handle_prompt
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/cli.py", line 44 in run
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00002e84 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 280 in _run_scheduler
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 953 in run
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.10/threading.py", line 973 in _bootstrap

Current thread 0x00000ef0 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 399 in show
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 849 in on_activate
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py", line 42 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 83 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 101 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 215 in run
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 34 in load_module
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 38 in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 18 in run
  File "C:/msys64/mingw64/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 139 in run
NativeCommandExitException: Program "Nicotine+.exe" ended with non-zero exit code: -1073741819.
```
</details>

**Comment by mathiascode** [comment]
I've rolled back a personal branch to a commit that previously started successfully for OP, so we can verify if a change in Nicotine+ or an external dependency is causing the crash. Can you try this build once it's ready? https://github.com/mathiascode/nicotine-plus/actions/runs/4039106810

Also, could you check if the crash occurs with a fresh config? (temporarily rename the C:\Users\<username>\AppData\Roaming\nicotine folder)

**Comment by tuhanayim** [comment]
Removed config, tested with provided build. Still the same issue.

**Comment by mathiascode** [comment]
What about the last build that still used GTK 4.8.2? https://github.com/nicotine-plus/nicotine-plus/actions/runs/3946829574

**Comment by tuhanayim** [comment]
This one works!

**Comment by mathiascode** [comment]
Good to know. Unfortunately, I can't reproduce the crash on my machine, so I'll have to send you builds until I've figured out exactly what update has caused the issue.

We can start with this build, should be ready in about 15 minutes: https://github.com/mathiascode/nicotine-plus/actions/runs/4039231396

**Comment by tuhanayim** [comment]
I just noticed when running Nicotine+, my discrete GPU runs it instead of onboard GPU, and it only crashes while running on discrete GPU. Tried [this build](https://github.com/nicotine-plus/nicotine-plus/actions/runs/4040689202), and it works with no problem. So I think there's a problem with currently used GTK4 (or libadwaita?) versions. Maybe bumping all GUI libraries (except majors) might fix the issue?

**Comment by mathiascode** [comment]
The build I linked above crashed as well?

I don't see any obvious regressions in GTK 4.8.3, but here's a build that only downgrades GTK to 4.8.2: https://github.com/mathiascode/nicotine-plus/actions/runs/4045289062

**Comment by tuhanayim** [comment]
> The build I linked above crashed as well?

Yes, sorry, I forgot to answer that.

> I don't see any obvious regressions in GTK 4.8.3, but here's a build that only downgrades GTK to 4.8.2: https://github.com/mathiascode/nicotine-plus/actions/runs/4045289062

Crashes again.

**Comment by mathiascode** [comment]
I found this change related to rendering that seems suspicious: https://github.com/msys2/MINGW-packages/commit/e19b3fb9bc4a10ca339b1252c1e593d8d11f571f

Here's a build with libepoxy downgraded (should be ready in a few minutes): https://github.com/mathiascode/nicotine-plus/actions/runs/4045699857

**Comment by mathiascode** [comment]
I don't think it's possible to downgrade these packages anymore without running into issues.

If you have time, could you set up a dev environment? Use these steps except for the "Build the applicaion" step: https://nicotine-plus.org/doc/PACKAGING.html#windows

When that's done, can you launch some smaller GTK demo applications like gtk4-widget-factory, gtk4-demo, and see if they crash?

**Comment by tuhanayim** [comment]
`gtk3-demo`, `gtk4-demo`, `gtk4-widget-factory` and `adwaita-1-demo` works perfectly.

**Comment by mathiascode** [comment]
Great! Can you also try running Nicotine+ with `./nicotine` in the nicotine-plus folder? I think there are some required dlls that are not included in our Windows builds at the moment.

**Comment by tuhanayim** [comment]
> Great! Can you also try running Nicotine+ with `./nicotine` in the nicotine-plus folder? I think there are some required dlls that are not included in our Windows builds at the moment.

And it works!

**Comment by mathiascode** [comment]
Does this build work? https://github.com/mathiascode/nicotine-plus/actions/runs/4046828015

**Comment by tuhanayim** [comment]
> Does this build work? https://github.com/mathiascode/nicotine-plus/actions/runs/4046828015

Works perfectly fine!

**Comment by mathiascode** [comment]
Awesome! I wonder if the GTK 3 builds need the same fix. Does the latest build in the 3.2.x branch work? https://github.com/nicotine-plus/nicotine-plus/actions/runs/4039972510

**Comment by tuhanayim** [comment]
> Awesome! I wonder if the GTK 3 builds need the same fix. Does the latest build in the 3.2.x branch work? https://github.com/nicotine-plus/nicotine-plus/actions/runs/4039972510

It works.

**Comment by mathiascode** [comment]
Right, GTK 3 doesn't use OpenGL for rendering the GUI.

I tried to remove some unnecessary files, can you verify if this build still works? https://github.com/mathiascode/nicotine-plus/actions/runs/4047294001

**Comment by tuhanayim** [comment]
> Right, GTK 3 doesn't use OpenGL for rendering the GUI.
> 
> I tried to remove some unnecessary files, can you verify if this build still works? https://github.com/mathiascode/nicotine-plus/actions/runs/4047294001

Sorry for late response, it works.

**Comment by tuhanayim** [comment]
Looks like commit made already. https://github.com/nicotine-plus/nicotine-plus/commit/0d41c6164b4312a84979a97b4ced4e3c9679f511

**Comment by mathiascode** [comment]
Thank you for testing! Could you confirm that the latest unstable build with 1e66dee89fdcd4e9c02954bab714dfb4d1be5fbe is working? If so, I will close this issue.

**Comment by tuhanayim** [comment]
Both `3.2.x` and `master` branch builds works.
