### ISSUE TITLE
 Show list of logged private chat users

### ISSUE THREAD

**Issue by Rings4** [nicotine-plus/nicotine-plus#2469]
### Describe the solution you'd like
One of the features holding me back from transitioning from SoulSeek-qt to Nicotine+ is the fact that closing a chat completely hides it. I want to be able to see all my past chats in a list, the same way the qt client does. Please refer to image.

I made this request in September, 2021 at #1509. It was closed because a basic history view was implemented in [7d71260](https://github.com/nicotine-plus/nicotine-plus/commit/7d71260e0455ec13348443ccdca343683ba1291e), which was stated that it could be polished further at a later point, if desired.

I don't agree that my issue should have been closed, because it's still not what I requested. At least, not yet. It's still just a list of usernames that you can access from the search bar, sorted alphabetically. It definitely needs polishing, so I do desire for that to be done, and am opening a new issue in hopes of that becoming reality. Again, this is the one feature holding me back from using nicotine+. I would really love to be able to keep track of what files of mine users download. I LOVE keeping track of that kind of stuff. I just simply cannot use this client with its almost non-existent chat feature.

I need a chat feature as shown below. Where I don't need to know the name of the person to chat with them. I want to see everyone's names and the last message that was sent, exactly like how qt does it.

Please make my request of ~2 years a reality. I eagerly await to hear back on any developments done in this area.

### Additional context
![image](https://user-images.githubusercontent.com/32050292/131620919-3e20fa33-44e1-4b59-86be-e33c4a937158.png)

**Comment by slook** [comment]
In Nicotine+ 3.3.0.dev5 ([master branch](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md)), the sort order of the "Latest Message" column (which starts with a datestamp) is remembered between sessions, such that the recent message of the Chat History popover is always at the top.

If that not the case, then there could be some bug, or otherwise you are confusing the old alphabetical drop down "v" list box of usernames in 3.2.x with the new "Chat History" popover feature that is being implemented presently in the [master branch](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) following your prior feature request.

Your ongoing suggestions for polishing the new feature before it is implemented into the stable releases would be much appreciated.

What build of Nicotine+ are you running?

**Comment by mathiascode** [comment]
3.2.x only has the username entry completion as you described.

The new conversation list is slated for Nicotine+ 3.3.0, but 3.3.0 was delayed for various reasons. It should be released in a few months, until then you can use the development builds.

**Comment by Rings4** [comment]
Thanks you two for the comments! I just tried running the latest development build of the Portable 64-bit Windows version, but it throws me this error:

![image](https://user-images.githubusercontent.com/32050292/229303544-a5ee6b1d-1693-4a62-852c-21f760d81d1e.png)

I then tried copying its files into my current stable portable version's folder and replacing all files it asked, and it gives me this:

![image](https://user-images.githubusercontent.com/32050292/229303568-bfbf5e3e-4f0f-4dc5-b91f-a63b4536f91f.png)

What should I do?

**Comment by slook** [comment]
> it throws me this error

The original error should not occur. It looks like some kind of problem with the path of one of the dependencies.

Is the same error encountered if you run the exe installer?

> What should I do?

Since both of your Nicotine+ installations are now broken, you should remove everything and start again.

I'd suggest finding the nicotine 'config' files in the users\~\Application Data folder to back it up, although it should not be removed even if you uninstall the application or switch between versions.

**Comment by Rings4** [comment]
> > it throws me this error
> 
> The original error should not occur. It looks like some kind of problem with the path of one of the dependencies.
> 
> Is the same error encountered if you run the exe installer?
> 
> > What should I do?
> 
> Since both of your Nicotine+ installations are now broken, you should remove everything and start again.
> 
> I'd suggest finding the nicotine 'config' files in the users~\Application Data folder to back it up, although it should not be affected even if you uninstall the application or switch between versions.

I was using the portable version, so all config files were in the program's folder, no? It didn't work even on its own, without merging into my previous installation.

**Comment by slook** [comment]
No, the portable version isn't really what most would define as portable, it does use the same config just it doesn't require installation. This is something that might change in future versions.

So, the portable 3.2.9 works on your system but not 3.3.0, is that correct?

**Comment by mathiascode** [comment]
The startup error was fixed in cx_Freeze a few hours ago: https://github.com/marcelotduarte/cx_Freeze/issues/1850

It will take a few days to make its way to the development builds of Nicotine+.

**Comment by mathiascode** [comment]
I added a temporary fix to our builds: https://github.com/nicotine-plus/nicotine-plus/commit/c7a27564c7c8891ee078f71deecda5015ab19d02

Try the latest portable build in about 20 minutes.

**Comment by slook** [comment]
@Rings4 The [latest build](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) should fix the issue, please let us know if this runs okay on your system. Thanks.

**Comment by mathiascode** [comment]
Anything that should still be done here?

**Comment by Rings4** [comment]
My apologies, I somehow missed the notification emails from this thread. I'll set a reminder to try it at my earliest convenience and report back!

**Comment by Rings4** [comment]
Apologies again for the delay! Been unexpectedly busy. I just now quickly set this up before bed to test it out and it looks like it indeed works! Thank you very much for your help!

I would just like to make one small suggestion, if I may: allow us to pin the "Chat History" button as the first chat tab, similar to soulseek-qt, where we can still have the button at the top, but also have the first tab be the same chat history. That way you can ctrl-tab or ctrl-shift-tab into it, without having to use the mouse to click the button at the top. And if you have too many chats open simultaneously, you can use the button at the top if that's more convenient.

**Comment by slook** [comment]
> suggestion, if I may: allow us to pin the "Chat History" button as the first chat tab

Marking this issue as Enhancement.

> small issue, but I don't seem to be able to have nicotine+ close to the system tray

That is expected because the system tray is being re-written to support GTK 4 see https://github.com/nicotine-plus/nicotine-plus/issues/2014#issuecomment-1243019328, but there is no Windows support yet.

**Comment by mathiascode** [comment]
> I would just like to make one small suggestion, if I may: allow us to pin the "Chat History" button as the first chat tab, similar to soulseek-qt, where we can still have the button at the top, but also have the first tab be the same chat history. That way you can ctrl-tab or ctrl-shift-tab into it, without having to use the mouse to click the button at the top. And if you have too many chats open simultaneously, you can use the button at the top if that's more convenient.

Before adding duplicate functionality, is ease of access the only issue here? You can already press Alt+H to open the chat history popover (although I could use another letter than H if that makes it easier to access using a single hand).

**Comment by mathiascode** [comment]
Any update regarding my last comment?

**Comment by Rings4** [comment]
Sorry for the lack of response, I missed the notification for this. Thanks for the follow up!

> Before adding duplicate functionality, is ease of access the only issue here? You can already press Alt+H to open the chat history popover (although I could use another letter than H if that makes it easier to access using a single hand).

Alt-H seems somewhat doable with a single hand, but I feel that having a button might still be nice as far as muscle memory goes. I'm personally all about hotkeys, so it's good to know about that one, but I sometimes remote into my PC using my phone and thus hotkeys become a chore to do.
