### ISSUE TITLE
Nicotine+ 3.3.2 Crash on Value: 'int' object has no attribute 'time_elapsed'

### ISSUE THREAD

**Issue by 501NotImplemented** [nicotine-plus/nicotine-plus#2947]
Nicotine+ version:  3.3.2
Operating System/Distribution: Win11
GTK Version: 4.12.5
Python Version: 3.11.8 (win32)

Type: <class 'AttributeError'>
Value: 'int' object has no attribute 'time_elapsed'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/iconnotebook.py", line 621, in on_focus_page
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 264, in on_focus
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 387, in update_model
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 434, in update_parent_rows
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 510, in update_parent_row

### Describe the bug
Nicotine+ crashed on switch to Downloads tab from Uploads tab.

### Expected behavior
The app should continue working. The UI should be updated correctly

### Steps to reproduce the bug
Start some active transfers
Open the Uploads tab when the new Upload has appeared.
Switch back to the Downloads tab.

### Additional context
The issue occurred only once for me but might be worth investigating.

**Comment by mathiascode** [comment]
This is not a programming error: https://github.com/nicotine-plus/nicotine-plus/blob/4bdd97f34732bc0ac88dcb2fc15ad3466fd633a9/pynicotine/gtkgui/transfers.py#L494-L512

If `transfer` was actually an integer, Nicotine+ would've crashed on line 495.

Since this issue is essentially the same as your previously reported issues, it seems increasingly likely that this is either a
1. hardware issue, most likely memory, or
2. something outside Nicotine+ screwing with memory

**Comment by mathiascode** [comment]
Could you try the Windows Memory Diagnostic Tool again, as well as MemTest86?

https://www.memtest86.com/
https://www.youtube.com/watch?v=EDCk04hgVEk

Have you run into any BSODs or crashes in other programs?

**Comment by 501NotImplemented** [comment]
@mathiascode I've had BSOD's previously, which were resolved by OS reinstall. Haven't caught them since then. I'll try to rerun Win Memory Diagnostic again on the weekends, last time it didn't find any issues, but it's a quite time-consuming check.

**Comment by slook** [comment]
Have you had opportunity to verify that you don't have faulty RAM in your machine?

Also, another test (that is quicker do) that can be run is does a SMART data check pass on your hard drive(s)?

**Comment by 501NotImplemented** [comment]
@slook yes, I haven't run the test yet, but decided to locate the faulty RAM plank, because I suspected that one of four planks (of same model) had issues. I've tried different configuration (running on 1 plank or 2 kits, mixing the pairs) and as of now - I've found the combination where I've got rid of those errors. Nicotine+ is running for 4 days, works as expected.

I suggest to close this ticket. However, I don't have a valid explanation what was the exact rootcause of the RAM issues on my side and why it was fixed in a such a naive way. Anyway, I'm happy that the issue is gone and thank you for your patience and investigation.

**Comment by mathiascode** [comment]
@501NotImplemented If possible, I suggest checking any files downloaded/modified in recent weeks for any obvious glitches/corruptions.

**Comment by slook** [comment]
@501NotImplemented I am glad you seem to have found the underlying hardware fault in your machine as a result of these investigations, and also thankful for you for providing debug logs and data that has helped make improvements.

Echoing as above I share the concern about file corruption that may still exist on your system, it would be a good idea to refrain from sharing until you have verified the integrity of your files.
