### ISSUE TITLE
wishlist searches should notify on finding a result, not on attempting to find something

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#380]
Not a biggy, but not really as I'd like it:

A wish list search causes a lightbulb each time the search is retried. And then you see an empty search result...

It would be nice if the search result would trigger a lightbulb is something was found.

Another solution would be a red lightbulb if nothing was found and a green one if something is found. Then you won't forget the wish list search is active.

**Comment by hboetes** [comment]
Or maybe this should be tagged enhancement.

**Comment by mathiascode** [comment]
Can you enable the "Search results" debug output? Either there's a bug or someone is sending spoofed/incorrect results.

**Comment by hboetes** [comment]
Wow, the weird things people are searching for. :-D

**Comment by hboetes** [comment]
Ah, that figures. I already have the file, in mp3 format so that matches my own file.

**Comment by hboetes** [comment]
Sooooo.... why does search include my own files? Should it really do that?

**Comment by mathiascode** [comment]
Seems like an oversight.

**Comment by mathiascode** [comment]
Should be fixed in this branch:
`git clone -b incorrectsearchresult https://github.com/mathiascode/nicotine-plus`

**Comment by hboetes** [comment]
Yes, much better! Thanks a lot.

**Comment by hboetes** [comment]
Running the latest master, after @kiplingw's commit.

So for testing purposes and because you may never know I'm searching for `john williams jane eyre Grace Poole And`

`01:16:38 User foobar is searching for john williams jane eyre Grace Poole And, returning 1 results`

Why would it return one result? The list is empty but does show `results: 0/1`

Something is still missing. Please reopen.

**Comment by hboetes** [comment]
Oh I figured it out, silly me. I also had a filter enabled: `flac` so it found an mp3 file match and filtered that one out.

Now I search for `john williams jane eyre Grace Poole flac` and that doesn't happen.
