### ISSUE TITLE
WinError 3, "the system cannot find the path specified"

### ISSUE THREAD

**Issue by jumperkballs** [Nicotine-Plus/nicotine-plus#920]
Nicotine+ version:  2.2.2
Operating System/Distribution: Win10 20H2 19042.630

### Describe the bug
Folder scan, whether initial scan or rescan, cannot parse folders. Python reports WinError 3, "the system cannot find the path specified".

There are 10 separate folders shared on this Nicotine installation. Within the settings sizes are reported for some, not for others.

Nicotine fails to complete scanning, appearing to crash with no further progress.

Bonus error: Nicotine failed to save config file, throwing WinError 183 ("Cannot create a file when that file already exists") until the %appdata% folder was hard linked to a different folder outside of c:\Users.

### Expected behavior
n/a

### Steps to reproduce the bug
n/a

### Additional context
Screenshots, logs, stacktraces or relevant information.

15:23:38 Error while scanning folder M:\main\Books\scifi, cult, horror and fantasy film and fiction zines\German Science Fiction in the Science-Fiction Magazines of Hugo Gernsback (1926-1935): [WinError 3] The system cannot find the path specified: 'M:\\main\\Books\\scifi, cult, horror and fantasy film and fiction zines\\German Science Fiction in the Science-Fiction Magazines of Hugo Gernsback (1926-1935)\\German Science Fiction in the Science-Fiction Magazines of Hugo Gernsback (1926-1935) - Linda Jordan (1986).pdf'
15:23:38 Error while scanning folder M:\main\Books\scifi, cult, horror and fantasy film and fiction zines\Terror! A History Of Horror Illustrations From The Pulp Magazines: [WinError 3] The system cannot find the path specified: 'M:\\main\\Books\\scifi, cult, horror and fantasy film and fiction zines\\Terror! A History Of Horror Illustrations From The Pulp Magazines\\A Pictorial History of Horror Stories - 200 Years of Spine-Chilling Illustrations from the Pulp Magazines - Peter Haining (1985, Treasure Press).cbr'
15:23:38 Error while scanning folder M:\main\workspace\youtube\not movies\Braingames_ Tales of Wrongovia (from Braingames #2, with _Braingames_ sign-on and sign-off): [WinError 3] The system cannot find the path specified: 'M:\\main\\workspace\\youtube\\not movies\\Braingames_ Tales of Wrongovia (from Braingames #2, with _Braingames_ sign-on and sign-off)\\Braingames_ Tales of Wrongovia (from Braingames #2, with _Braingames_ sign-on and sign-off) (480p_30fps_H264-128kbit_AAC).English.srt'
15:23:38 Error while scanning folder M:\main\workspace\youtube\not movies\Braingames_ Whosamawhatchamacallits (from Braingames #5, with _Braingames_ sign-on and sign-off): [WinError 3] The system cannot find the path specified: 'M:\\main\\workspace\\youtube\\not movies\\Braingames_ Whosamawhatchamacallits (from Braingames #5, with _Braingames_ sign-on and sign-off)\\Braingames_ Whosamawhatchamacallits (from Braingames #5, with _Braingames_ sign-on and sign-off) (480p_30fps_H264-128kbit_AAC).mp4'
15:23:38 Error while scanning folder M:\main\workspace\youtube\not movies\Drive-in theater vintage short films - late 50s, early 60s - intermission, refreshments- cartoons!: [WinError 3] The system cannot find the path specified: 'M:\\main\\workspace\\youtube\\not movies\\Drive-in theater vintage short films - late 50s, early 60s - intermission, refreshments- cartoons!\\Drive-in theater vintage short films - late 50s, early 60s - intermission, refreshments- cartoons! (360p_30fps_H264-96kbit_AAC).English.srt'
15:23:38 Error while scanning folder M:\main\workspace\youtube\not movies\Kellogg's Rice Krispies Squares - The World's First 3D Cinema Ad You Can Taste (2012, UK, 3D): [WinError 3] The system cannot find the path specified: "M:\\main\\workspace\\youtube\\not movies\\Kellogg's Rice Krispies Squares - The World's First 3D Cinema Ad You Can Taste (2012, UK, 3D)\\3D  Kellogg's Rice Krispies Squares - The World's First 3D Cinema Ad You Can Taste (2012, UK, 3D) (1080p_24fps_H264-128kbit_AAC).English.srt"
15:23:38 Error while scanning folder M:\main\workspace\youtube\not movies\固 End of 35mm film distribution puts many drive-in theaters new digital in jeopardy of closure 庆 愁: [WinError 3] The system cannot find the path specified: 'M:\\main\\workspace\\youtube\\not movies\\固 End of 35mm film distribution puts many drive-in theaters new digital in jeopardy of closure 庆 愁\\固 End of 35mm film distribution puts many drive-in theaters new digital in jeopardy of closure 庆 愁 (480p_30fps_H264-128kbit_AAC).mp4'
15:23:38 Error while scanning folder N:\main\workspace\torrents\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\Philip Marlowe-Private Eye.Season.1.DVDRip.XviD.1983\2. The King in Yellow: [WinError 3] The system cannot find the path specified: 'N:\\main\\workspace\\torrents\\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\\Philip Marlowe-Private Eye.Season.1.DVDRip.XviD.1983\\2. The King in Yellow\\Philip Marlowe-Private Eye Collection.Season 1.e2. The King in Yel.1983-1986.DVDRip.XviD.nfo'
15:23:38 Error while scanning folder N:\main\workspace\torrents\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\Philip Marlowe-Private Eye.Season.1.DVDRip.XviD.1983\5. Smart Aleck Kill: [WinError 3] The system cannot find the path specified: 'N:\\main\\workspace\\torrents\\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\\Philip Marlowe-Private Eye.Season.1.DVDRip.XviD.1983\\5. Smart Aleck Kill\\Philip Marlowe-Private Eye Collection.Season 1.e5. Smart Aleck Kill.1983-1986.DVDRip.XviD.nfo'
15:23:38 Error while scanning folder N:\main\workspace\torrents\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\1.Blackmailers Don't Shoot: [WinError 3] The system cannot find the path specified: "N:\\main\\workspace\\torrents\\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\\1.Blackmailers Don't Shoot\\Philip Marlowe-Private Eye Collection.Season 2.e1.Blackmailers1983-1986.DVDRip.XviD.nfo"
15:23:38 Error while scanning folder N:\main\workspace\torrents\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\3.Pickup on Noon Street: [WinError 3] The system cannot find the path specified: 'N:\\main\\workspace\\torrents\\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\\3.Pickup on Noon Street\\Philip Marlowe-Private Eye Collection.Season 2.e3.Pickup on Noon.1983-1986.DVDRip.XviD.nfo'
15:23:38 Error while scanning folder N:\main\workspace\torrents\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\4.Guns at Cyrano's: [WinError 3] The system cannot find the path specified: "N:\\main\\workspace\\torrents\\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\\4.Guns at Cyrano's\\Philip Marlowe-Private Eye Collection.Season 2.e4.Guns at Cyrano's.1983-1986.DVDRip.XviD.nfo"
15:23:38 Error while scanning folder N:\main\workspace\torrents\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\5.Trouble Is My Business: [WinError 3] The system cannot find the path specified: 'N:\\main\\workspace\\torrents\\Philip Marlowe-Private Eye Collection.Season 1-2.1983-1986.DVDRip.XviD\\Philip Marlowe-Private Eye.Season.2.DVDRip.XviD.1986\\5.Trouble Is My Business\\Philip Marlowe-Private Eye Collection.Season 2.e5.Trouble Is My Business.1983-1986..nfo'

**Comment by mathiascode** [comment]
Are the files valid, and are there any permission issues or similar? I'm not sure what the issue could be, as Python is responsible for finding and reporting the files in the first place.

**Comment by jumperkballs** [comment]
The files are valid and the permissions are fine. The files above all have paths of greater than 260 characters. This is a relatively fresh Windows install, from October, and I had forgotten to enable long paths within Windows for 32 bit programs, which rectifies the issue. I believe the version of python installed with Nicotine is the 32 bit version. The 64 bit version of Python doesn't have this path length limitation, iirc.

For the WinError 183, "Cannot create a file when that file already exists" issue I also tried running Nicotine Plus as admin and received the same issue.

I also added several users to my buddy list that are all appearing offline despite their appearing online and browsable to a normal Soulseek installation on another PC. All ports are forwarded correctly.

Honestly not sure why I'm encountering so many issues with Nicotine but one of them has been rectified.

**Comment by jumperkballs** [comment]
Sorry to delete my previous comment, wanted to do more troubleshooting. I thought it was a 260 path length issue, but it wasn't. This is a fresh Windows install from October. Permissions are fine. The files are valid. I was using the portable x64 version of Nicotine Plus, deleted that and installed the x64 version. All of the issues persist whether using a standard user account or an administrator.

I went back to Nicotine Plus 2.1.1 and that appears to have eliminated the WinError 3 issue, at least it threw no errors. WinError 183 still persists, as does the error in which Nicotine Plus says that users are offline which are online to a normal Soulseek install.

Really dunno what to do here. Are there any troubleshooting/debug methods I can take to help?

**Comment by jumperkballs** [comment]
OK, the userlist issue appears to be my bad. I had no idea Soulseek usernames were case sensitive and I've been using this software since 2000, I don't think I've ever manually added a username and just assumed. Jesus Christ. I really hate how stuck Soulseek is in the extremely poor decisionmaking and programming of its roots.

So it looks like I'm down to WinError 183 persisting. User account has full access to the %appdata% folder, and when I mklink /D the %appdata%/roaming/nicotine folder into a folder outside of the privileged Users folder it works fine. I'd rather not have to kludge it. Any ideas?

**Comment by mathiascode** [comment]
This should be fixed in the latest unstable build. https://github.com/Nicotine-Plus/nicotine-plus/issues/934

**Comment by redactedscribe** [comment]
I am getting the `[WinError 3]` error on startup of Nicotine+ `2.2.2`.

I've tried upgrading my Python `3.7.9` to the latest `3.9.1` available to me.
I've run Nicotine+ without Python installed (not sure how this was possible, maybe it is bundle with Nicotine+?).
I've tried downgrading to Nicotine+ `2.2.1` but the problem persists.
My system has long file paths enabled. I've checked this recently (both `gpedit.exe` and `regedit` reported that it's enabled).

Dragging any of the files Nicotine+ has issue with from File Explorer to my media player for example, does not succeed. Double-clicking the file also will not open via the player either. Interestingly, dragging from one File Explorer to another _does_ work - it is copied. Dragging an `.m3u` playlist file (<260) that references a file that I know to have a file path >=260 characters, the file is loaded into the media player _and is playable_. Rewriting the metadata of the file is possible via Mp3tag too. Since programs can read and write to these files, I think that means Nicotine+ needs a fix of some sort.

**Comment by mathiascode** [comment]
@redactedscribe As the unstable 64-bit Windows builds now work again, could you check if this issue still occurs in them?

> I've run Nicotine+ without Python installed (not sure how this was possible, maybe it is bundle with Nicotine+?).
Yes, Python is bundled.

**Comment by redactedscribe** [comment]
I wouldn't have noticed that Windows dev builds were available if you hadn't pointed it out. Thanks 🙂

And good news, the issue isn't present in `2.3.0.dev1`.
